# Generated by Django 5.2.3 on 2025-08-15 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Ceo', models.CharField(max_length=50)),
                ('Origin', models.CharField(max_length=50)),
                ('Est_Year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Seat_Capacity', models.IntegerField()),
                ('Fuel_type', models.CharField(max_length=50)),
                ('Top_Speed', models.IntegerField()),
                ('Milage', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Compaines', to='Firstapp.company')),
            ],
        ),
    ]
